language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - pip install --upgrade pip setuptools zc.buildout coveralls coverage==3.7 createcoverage
  - buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - createcoverage
  - coveralls

notifications:
  email:
    - jk@kleinundpartner.at
