language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
install:
  - pip install --upgrade pip setuptools zc.buildout coveralls coverage==3.7 createcoverage
  - buildout -Nc travis.cfg buildout:eggs-directory=$HOME/buildout-cache/eggs buildout:download-cache=$HOME/buildout-cache/downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - createcoverage
  - coveralls

notifications:
  email:
    - jk@kleinundpartner.at
